version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "NuGet.Configuration"
      - dependency-name: "Microsoft.CodeAnalysis"
      - dependency-name: "Microsoft.CodeAnalysis.Analyzers"
      - dependency-name: "Microsoft.CodeAnalysis.CSharp"
      - dependency-name: "Microsoft.CodeAnalysis.CSharp.Workspaces"
      - dependency-name: "Microsoft.CodeAnalysis.Workspaces.Common"
      - dependency-name: "NUnit3TestAdapter"
    open-pull-requests-limit: 1
    groups:
        all-dependencies:
          patterns:
            - "*"